spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://mysql:3306/movielister
        username: lofaszjoska
        password: lofaszjoska
        driver-class-name: com.mysql.jdbc.Driver